package com.nevoit.cresto.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate

/**
 * Represents a single to-do item entity for the Room database.
 *
 * @property id The unique identifier for the to-do item. Auto-generated by the database.
 * @property title The main text or title of the to-do item.
 * @property dueDate The optional due date for the to-do item.
 * @property isCompleted A boolean flag indicating whether the to-do item has been completed.
 * @property hashtag An optional string for tagging or categorizing the to-do item.
 * @property flag An optional integer flag, can be used for priority or other categorizations.
 */
@Entity(tableName = "todo_items")
data class TodoItem(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val dueDate: LocalDate? = null,
    val isCompleted: Boolean = false,
    val hashtag: String? = null,
    val flag: Int = 0
)
